<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Wpf.Clippy</RootNamespace>
    <AssemblyName>Wpf.Clippy</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>1.1.0</Version>
    <Description>Bring back animated clippy characters to your WPF applications</Description>
    <Authors>Sam Oates Games</Authors>
    <Company>Sam Oates Games</Company>
    <Product>Wpf.Clippy</Product>
    <Copyright>Copyright Sam Oates Games © 2024</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/samoatesgames/Clippy.WPF</PackageProjectUrl>
    <RepositoryUrl>https://github.com/samoatesgames/Clippy.WPF</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\data.json" />
    <Resource Include="Resources\**\map.png" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="packages.config" />
    <None Remove="Wpf.Clippy.nuspec" />
  </ItemGroup>

</Project>
